### ISSUE TITLE
problem with ->moveToFolder() and multiple moves

### ISSUE THREAD

**Issue by mundanet** [Webklex/laravel-imap#31] opened 2017-10-17 19:35 UTC
->moveToFolder() works perfectly when moving a single email in a single session.
But it fails to move correct emails when moving more than one email per session.
Debugging with xdebug I can confirm that the sequence numbers got confused when expunging messages.
I find the affirmations at the following link to be correct:
http://gabijack.com/moving-and-deleting-messages-with-php-imap/

May I request a fix?

**Comment by Webklex** [comment] 2017-10-17 19:46
Hi @mundanet ,
thanks for your report. You are always welcome to  suggest any fix or feature :)
I will verify this issue and provide an update as soon as possible. 

Best regards

**Comment by mundanet** [comment] 2017-10-17 22:06
HI @Webklex I have tested a solution:
Client.php
    /**
     * Messages to be deleted
     *
     * @var array
     */
    public $msglist = [];

    /**
     * Move marked messages to Folder.
     *
     * @param string $mailbox
     *
     * @return boolean
     */
    public function moveToFolder($mailbox = 'INBOX') {
        $this->checkConnection();
        $this->createFolder($mailbox);

        if(imap_mail_move($this->connection, implode(',', $this->msglist), $mailbox) == true){
            return $this->expunge();
        }
        return false;
    }

in Message.php
    /**
     * mark the Message to be moved into another Folder
     *
     *
     * @return bool
     */
    public function markToBeMoved(){
        array_push($this->client->msglist, $this->msglist);
    }

and it is working.
Not the nicest code but it is a good starting point

**Comment by Webklex** [comment] 2017-10-18 20:51
Hi @mundanet ,
I just released a new version. Thanks for your suggestions and support :)

Please reffer to: [v1.0.3.5](https://github.com/Webklex/laravel-imap/releases/tag/1.0.3.5)

**Comment by theparker** [comment] 2019-04-03 13:52
@Webklex 
I am having a same issue with `$message->moveToFolder()` 
The error I get from `imap_last_error()` is `[CLOSED] IMAP connection lost`
The first few messages are moved successfully but after moving roughly 8 messages, I consistently get the connection lost error. 
Is there a way to say increase connection timeout? I was thinking the `checkConnection()` function which is called in `createFolder()` should reestablish connection but it doesn't seem like that works like it is supposed to.
What would you suggest?

**Comment by theparker** [comment] 2019-04-09 09:28
It seems the problem is coming from calling `$client->createFolder();` inside `$message->moveToFolder()` as commenting it out works.

I don't know if it is a bug, i.e. should have been  `$client->checkConnection()` instead of `$client->createFolder()` but you may want to consider removing `createFolder()` from `moveToFolder()` as calling `moveToFolder()` a thousand times would mean a thousand attempt to create the same folder.

PS; Thanks for the effort in creating and maintaining this library. I like the idea of having message and attachment objects.

**Comment by gareth-ib** [comment] 2019-04-11 01:01
I'm having a similar problem.
Both folders get created when the code runs, but the email it finds gets moved into the `processed` folder, but doesn't move into the `review` folder.
I don't see anything in the code indicating why this would be happening. Any ideas?
Thanks!

```php
namespace App\Console\Commands;

use Illuminate\Console\Command;
use Webklex\IMAP\Client as ImapClient;

class ImapTest extends Command
{
    protected $signature = 'ImapTest';

    public function handle()
    {
        
        $oClient = new ImapClient([
            'host'          => 'imap.gmail.com',
            'port'          => 993,
            'encryption'    => 'ssl',
            'validate_cert' => true,
            'username'      => env( 'EMAIL_USERNAME' ),
            'password'      => env( 'EMAIL_APP_PASSWORD' ),
            'protocol'      => 'imap'
        ]);
        
        $folder = $oClient->getFolder('INBOX');
        
        /**
         * @var \Webklex\IMAP\Support\MessageCollection $messages
         */
        $messages = $folder->messages()->limit(1)->get();
        
        /**
          * @var \Webklex\IMAP\Message $message
          */
        foreach( $messages as $message ) {
            $message->moveToFolder('processing');
            sleep(5);
            $message->moveToFolder('review');
        }

    }

}
```

**Comment by theparker** [comment] 2019-04-11 08:37
@gareth-ib Use `imap_last_error()` after the last call to `moveToFolder()` to see what errors are returned. 

I think after moving the message to the processing folder, you could reload the message object (as it likely will be referencing the message in the initial folder) before moving to the review folder or you could call `$client->expunge()` before the second call to `moveToFolder()`

Either way, checking imap errors should help you identify the problem.

**Comment by gareth-ib** [comment] 2019-04-11 17:28
I tried your idea...
```php
            $message->moveToFolder('processing');

            sleep(5);

            $oClient->expunge();

            $message->moveToFolder('review');
            $error = imap_last_error();
            dump($error);

            $oClient->expunge();

            $message->move('review');
            $error = imap_last_error();
            dump($error);
```
and got...

```
"[ALREADYEXISTS] Duplicate folder name review (Failure)"
"Could not parse command"
```

with the email still sitting in the `processing` folder

**Comment by theparker** [comment] 2019-04-12 08:10
Comment out `$this->client->createFolder($mailbox);` in the `moveToFolder()` function in `webklex/php-imap/src/Message.php` and try again.

I fixed the issue I was having with lost  connection by commenting that code out. I don't think a call to `moveToFolder()` should attempt creating a folder.

```php
/**
     * Move the Message into an other Folder
     * @param string $mailbox
     *
     * @return bool
     * @throws Exceptions\ConnectionFailedException
     */
    public function moveToFolder($mailbox = 'INBOX') {
        //$this->client->createFolder($mailbox); /*Todo: Reference: https://github.com/Webklex/laravel-imap/issues/31*/

        return imap_mail_move($this->client->getConnection(), $this->uid, $mailbox, CP_UID);
    }
```

**Comment by gareth-ib** [comment] 2019-04-12 17:32
with the `createFolder` commented out...
```
false
"Could not parse command"
```
and the mail is still in the `processing` (first) folder

**Comment by Webklex** [comment] 2019-04-12 19:13
Hi @gareth-ib ,
plase try to use `INBOX.processing` or `INBOX/processing` depending on your delimiter as `$mailbox` instead.

You might also want to update to the latest version or perhaps the master for futher investigation :)

Best regards

**Comment by gareth-ib** [comment] 2019-04-12 19:39
@Webklex ok I apparently was on 1.2, so I upgraded to 1.4...
I ran it with the variations of the `INBOX` included in the folder name, and the results were the same. But into new folders as seen

![image](https://user-images.githubusercontent.com/29517750/56061881-9368d080-5d1f-11e9-9ac7-65a9ad0a402c.png)

no prefix...
```
"[ALREADYEXISTS] Duplicate folder name review (Failure)"
"Could not parse command"
```

`INBOX/` prefix
```
false
"Could not parse command"
```

`INBOX.` prefix ( these folders already existed )
```
"[ALREADYEXISTS] Duplicate folder name INBOX.review (Failure)"
"Could not parse command"
```

**Comment by Webklex** [comment] 2019-04-12 20:17
Hi @gareth-ib,
I found the issue and provided a fix.

The MessageID or UID changes by moving the message. Therefore it wasn't possible to move the same Message/UID again.

The provided patch does exactly that. 
The target mailbox will return the next UID and return a new message instance based on it if the message could be moved. The returned message has now a valid and fresh UID which can be moved again. 

Please give the current master version a try. If it works as expected I will release a new version :)

Best regards

**Comment by gareth-ib** [comment] 2019-04-12 20:30
okay I've got it updated...
```bash
  - Removing webklex/laravel-imap (1.4.0)
  - Installing webklex/laravel-imap (dev-master 6990abb): Downloading (100%)
```
and the code...
```php
            $message->moveToFolder('processing');

            sleep(5);

            $oClient->expunge();

            $message->moveToFolder('review');
            $error = imap_last_error();
            dump($error);

            $oClient->expunge();

            $message->move('review');
            $error = imap_last_error();
            dump($error);
```
output ( same result if I remove the `$oClient->expunge();` commands )
```
"[ALREADYEXISTS] Duplicate folder name review (Failure)"
"Could not parse command"
```

**Comment by gareth-ib** [comment] 2019-04-12 20:30
this is on Gmail by the way, if that helps

**Comment by Webklex** [comment] 2019-04-12 20:46
Remember [Message::moveToFolder()](https://github.com/Webklex/laravel-imap#messageclass) returns the new Message (the moved instance). The old instance is now no longer valid.

```php
echo "message UID: ".$message->uid."\n";

$processing_message = $message->moveToFolder('processing', true, false);
sleep(5);

if($processing_message !== null){
    echo "processing UID: ". $processing_message->uid."\n";

    $review_message = $processing_message->moveToFolder('review', true, false);
    if($review_message !== null){
        echo "review UID: ". $review_message->uid."\n";
    }else{
        dd(imap_last_error());
    }
}else{
    dd(imap_last_error());
}
```

Best regards

**Comment by gareth-ib** [comment] 2019-04-12 20:54
I added an echo into the `moveToFolder`
```php
        if($status === true){
            if($expunge) $this->client->expunge();
echo __LINE__.':'.$target_status->uidnext."\n";
            return $target_folder->getMessage($target_status->uidnext);
        }
```
and ran the code...
```php
            $movedMessage = $message->moveToFolder('processing');
            dd($movedMessage);
            sleep(5);
            $movedMessage->moveToFolder('review');
```
and the result is...
```bash
967:15
null
```

**Comment by Webklex** [comment] 2019-04-12 20:57
And if us use this it is `null` as well?
```php
$movedMessage = $message->moveToFolder('processing', true, false);
```

**Comment by gareth-ib** [comment] 2019-04-12 20:58
yeah ran it with your demo test code and the result is...
```
message UID: 906
false
```

**Comment by gareth-ib** [comment] 2019-04-12 21:01
oh no I don't do anything to the $message before the move, it's just like the loop I posted orginally

**Comment by Webklex** [comment] 2019-04-12 22:21
I found an other issue when handling with multiple connections. This should get rid of it and finally solve your problem :)

**Comment by gareth-ib** [comment] 2019-04-12 22:24
hooraayy! thanks! looks like it was a lot of changes! haha

**Comment by gareth-ib** [comment] 2019-04-12 22:24
oh I confirmed it works btw :)

**Closed** 2019-04-12 22:25 UTC
Labels: bug, validated

**Comment by gareth-ib** [comment] 2019-04-15 19:08
found a problem with the returned message not having attachments like the orig message did. submitted PR #209
