### ISSUE TITLE
New config not recognized?

### ISSUE THREAD

**Issue by DasTobbel** [Webklex/laravel-imap#344] opened 2020-10-06 08:40 UTC
Hello there,
after upgrading from 1.6.2 to 2.0.2, publishing the new config, clearing all the laravel caches, even removing and reinstalling via composer i'm stuck at this error:
```
ErrorException  : Trying to access array offset on value of type null
  at /home/tobbel/git/xxx/vendor/webklex/php-imap/src/Client.php:242

```

while testing the configs i added the events and masks to my client - config:
```
[...]
use Webklex\PHPIMAP\Client;
[...]
    public function handle() {
        [...]
        $oClient = new Client([
            'host' => $imap['server'],
            'port' => $imap['port'],
            'encryption' => $imap['security'],
            'validate_cert' => (true === $imap['allowUnsecure']) ? false : true,
            'username' => $imap['user'],
            'password' => $imap['password'],
            'protocol' => 'imap',
            'authentication' => null,
            'events' => [
                "message" => [
                    'new' => \Webklex\IMAP\Events\MessageNewEvent::class,
                    'moved' => \Webklex\IMAP\Events\MessageMovedEvent::class,
                    'copied' => \Webklex\IMAP\Events\MessageCopiedEvent::class,
                    'deleted' => \Webklex\IMAP\Events\MessageDeletedEvent::class,
                    'restored' => \Webklex\IMAP\Events\MessageRestoredEvent::class,
                ],
                "folder" => [
                    'new' => \Webklex\IMAP\Events\FolderNewEvent::class,
                    'moved' => \Webklex\IMAP\Events\FolderMovedEvent::class,
                    'deleted' => \Webklex\IMAP\Events\FolderDeletedEvent::class,
                ],
                "flag" => [
                    'new' => \Webklex\IMAP\Events\FlagNewEvent::class,
                    'deleted' => \Webklex\IMAP\Events\FlagDeletedEvent::class,
                ],
            ],
            'masks' => [
                'message' => \Webklex\PHPIMAP\Support\Masks\MessageMask::class,
                'attachment' => \Webklex\PHPIMAP\Support\Masks\AttachmentMask::class
            ],
        ]);

        $oClient->connect();
        [...]
    }
[...]
```

Afther that change, the only difference was the location of the error message:
```
ErrorException  : Trying to access array offset on value of type null
  at /home/tobbel/git/xxx/vendor/webklex/php-imap/src/Client.php:199

```
after adding some Logging i narrowed it down, in the setXXXFromConfig functions, it's trying to access the default config and add the events/masks, but those default parts are empty (Probaby they should come from the app->config->imap). 
Even logging inside the "php-imap/Client.php" and inside of the ClientManager Classes showed only empty application config objects.

I'm calling this from a console command and dispatch this to a job, does this interfere with the way of accessing the configuration?
Or am I supposed to do something further after upgrading?
Php version: 7.4.3
Laravel 6.x

Cheers and thanks!

**Comment by ricus-zero2one** [comment] 2020-10-07 10:17
+1 to this - also testing out version 2 and got the same error even after ensuring I have all the new config options

My setup is similar in that I'm also dispatching jobs that process a bunch of different mailboxes, setting the config in the Client constructor for every mailbox that gets synced

**Comment by robtesch** [comment] 2020-10-07 16:23
+1 same here, been debugging this for days now with no real luck.

**Comment by Webklex** [comment] 2020-10-08 18:18
Hi @DasTobbel @ricus-zero2one @robtesch  ,
thanks for your report. I was able to reproduce the problem and just released a patch. Please update to the latest version, update your `config/imap.php` config file and try again.

Best regards,

**Comment by ricus-zero2one** [comment] 2020-10-09 10:27
Hi @Webklex I did a fresh update and I'm on the current versions:

```
 - Installing webklex/php-imap (2.1.9): Downloading (100%)         
  - Updating webklex/laravel-imap (1.6.2 => 2.1.0): Downloading (100%)     
```

I'm making an instance of the Webklex\PHPIMAP\Client class manually in the following way:

```
 $oClient = new Client([
                'username'      => $this->username,
                'password'      => $this->password,
                'host'          => $this->host,
                'port'          => $this->port,
                'encryption'    => $this->encryption,
                'protocol'      => $this->protocol,
                'validate_cert' => $this->validate_cert,
            ]);
```

Creating the above Client instance throws

```
local.ERROR: ErrorException: Trying to access array offset on value of type null in /Users/ricus/dev/secret-project-name/vendor/webklex/php-imap/src/Client.php:242
```

I dug into this a little more, the errors occurs as soon as I try and new up the Client class with the above snippet, line 242 as indicated above.

The code is attempting to get the key `message` from the `$default_config` array. I dumped that array and it's null at that stage.

Inside `setConfig` of `Client.php` the two `ClientManager::get` calls are both returning null for me - which is where this error seems to be stemming from.

The ClientManager class's constructor wants a default config, which is not set with the static access to the get method.

I noticed that the `ClientManager` of php-imap is now used instead of the one in laravel-imap. When it was using the laravel-imap version, your service provider injected the config when resolving the class:

```
 $this->app->singleton(ClientManager::class, function($app) {
            return new ClientManager($app['config']["imap"]);
        });
```

It seems like this config isn't getting set anymore with the move to php-imap? Which doesn't really make sense because if that is the case I would it breaks for everyone.

I hope this helps, or let me know if there is something else I should be doing.

**Comment by Webklex** [comment] 2020-10-09 11:22
Hi @ricus-zero2one ,
thanks for the update. I added a new function to hopefully solve this issue [13e76da](https://github.com/Webklex/php-imap/commit/13e76da3cdb547819012ecabe7b96f2dfee1d7be) once and for all :)

You are right, if the ClientManager instance is not loaded, the config is not available and therefor the "app" crashes. By using `\Webklex\IMAP\Facades\Client::make($options)` this can be prevented.

Best regards and thank you so much for testing and writing awesome reports :+1:

**Comment by ricus-zero2one** [comment] 2020-10-09 11:54
Thanks for the quick feedback @Webklex 

I'll get this tested as soon as possible my side.

Quick initial tests indicate that I can now create the client successfully, however I'm having some other issues with previously working code, for instance 

```php
       //$conn is instance of Webklex\PHPIMAP\Client
       $inbox = $conn->getFolder('INBOX');

        $messages = $inbox->query()->limit(2)->get();
```

I'm getting no results:

```php
Webklex\PHPIMAP\Support\MessageCollection {#1421 ▼
  #total: null
  #items: []
}
```

however if I run the same code on version 1.x I get

```php
Webklex\IMAP\Support\MessageCollection {#1373 ▼
  #total: 348
  #items: array:2 [▼
    "CAE2pCLvgGk6eb01dB+rys+8hb9Yyyiurwauesa9rMam3JHQOOw@mail.gmail.com" => Webklex\IMAP\Message {#1418 ▶}
    "CAE2pCLtPBk0KBcY9vmSu10GxOH6UPd_aqMfDYm73UKMz6P1n+g@mail.gmail.com" => Webklex\IMAP\Message {#1453 ▶}
  ]
}
```

So for some reason the same code on version 1.x is getting the 2 emails but on version 2.x is not.

I'll need to dig into this a bit deeper when I get a chance to try and help get to the bottom of why this might be, thanks again for this great package.

Best regards

**Comment by DasTobbel** [comment] 2020-10-12 09:55
Thanks for the Update @Webklex !
So far its recieving the emails on my end.
I also tried @ricus-zero2one's code with the limiting - also no messages, without limiting its fine.
```php
  //Empty result set
  $folder = $oClient->getFolder('INBOX');
  $messages = $folder->query()->limit(2)->get();
  dump(["with limit" => count($messages)]);
  // array:1 [  "with limit" => 0 ]

  // Working -> many results
  $folder = $oClient->getFolder('INBOX');
  $messages = $folder->query()->since(Carbon::now()->subDays(30))->get();
  dump(["with since" => count($messages)]);
  // array:1 [  "with since" => 7 ]
```

Another strange behaviour on my side: I cannot move mails anymore.
`$message->moveToFolder($folder, $expunge, $createFolder)` is gone, so i switched to `$message->move($folder, $expunge)`, but nothing happens.
I looked into the message.php , added some dumps at copy/move:
```php
// Message.php
    public function copy($folder)
    {
        dump([ 'folder' => $folder]); // [3]
        $this->client->openFolder($this->folder_path);
        $status = $this->client->getConnection()->examineFolder($folder);
        dump([ 'status' => $status]); // [4]
        /** @var Folder $folder */
        $folder = $this->client->getFolder($folder);
        dump([ 'folderAfterClient' => $folder]); // [5]
        dump([ 'client' => $this->client]); // [5.1]

        if (isset($status["uidnext"]) && $folder !== null) {
            $next_uid = $status["uidnext"];
            if ($this->client->getConnection()->copyMessage($folder->path, $this->msgn) == true) {
                $this->client->openFolder($folder->path);
                $message_num = $this->client->getConnection()->getMessageNumber($next_uid);

                $message = $folder->query()->getMessage($message_num);
                $event = $this->getEvent("message", "copied");
                $event::dispatch($this, $message);

                return $message;
            }
        }

        return null;
    }


 public function move($folder, $expunge = false)
    {
        dump([ 'folder' => $folder]); // [1]
        dump([ 'expunge' => $expunge]); // [2]
        $message = $this->copy($folder);
        if ($message !== null) {
            $this->delete($expunge);

            $event = $this->getEvent("message", "moved");
            $event::dispatch($this, $message);
        }
        dump(['message' => $message]); // [6]
        return $message;
    }
// Responses
/*
[1] Limiters are fine, path correct: "folder" => "My/Path" 
[2] expunge is true in my call:  "expunge" => true 
[3] "folder" => "My/Path" 
[4] Looks good to me:
         array:1 [
           "status" => array:5 [
             "flags" => array:1 [
               0 => array:6 [
                 0 => "\Answered"
                 1 => "\Flagged"
                 2 => "\Deleted"
                 3 => "\Seen"
                 4 => "\Draft"
                 5 => "NonJunk"
               ]
             ]
             "exists" => "8"
             "recent" => "0"
             "uidvalidity" => 1535248778
             "uidnext" => 9
           ]
         ]
[5]  now it gets wierd: "folderAfterClient" => null
[5.1] Client loogs good to me array:1 [  "client" => Webklex\PHPIMAP\Client {#1468 ......} ]
[6] No message copied because it was not able to find the folder -> null ...
*/
```
with the dumps it narrowed down: **The `$message->move()` function does not allow nested folders!**  A small change in Message.php of `$this->client->getFolder($folder)` to `$this->client->getFolderByPath($folder);` fixed it for me.

Now to my question: Is this intended? 
The old "moveToFolder" accepted paths/names, maybe a small wrapper which splits/identifies delimiters in "Client::getFolder()"?
```php
```php
  public function getFolder($folder_name, $delimiter = '.')
  {
      if (strpos($folder_name, $delimiter) !== false) {
        return $this->getFolderByPath($folder_name);
      } 
      return $this->getFolderByName($folder_name);
  }
```

Cheers!
```

**Comment by Webklex** [comment] 2020-10-12 10:22
Hi @DasTobbel ,
thanks for the detailed report. You are correct and I like your suggestion. Would you mind to create a PR? Otherwise I'll patch it in in the next few days :)

Best regards,

**Comment by Webklex** [comment] 2020-10-12 10:25
Hi @ricus-zero2one @DasTobbel ,
please try to add at least one condition to the query:
```php
$messages = $inbox->query()->all()->limit(2)->get();
```

Best regards,

**Comment by Webklex** [comment] 2020-10-13 05:40
Hi @DasTobbel ,
thanks for your pr. A new version is already available :)

Best regards,

**Comment by ricus-zero2one** [comment] 2020-10-15 11:31
Hi @Webklex 

I got around to testing this again, but I'm running into some more issues.

Im on webklex/php-imap version 2.1.13 and webklex/laravel-imap 2.1.13

I've changed my connection code to make use of the ClientManager as on the php-imap docs:

```php
  $cm = new ClientManager(config("imap"));

            $oClient = $cm->make([
                'username'      => $this->username,
                'password'      => $this->password,
                'host'          => $this->host,
                'port'          => $this->port,
                'encryption'    => $this->encryption,
                'protocol'      => $this->protocol,
                'validate_cert' => $this->validate_cert,
            ]);

            $this->connection = $oClient->connect();
```

I then proceed to get the Inbox folder:

```php
 $inbox = $conn->getFolder('INBOX'); //$conn is the result of the calling ->connect() on the client
```

which dumps as:

```
Webklex\PHPIMAP\Folder {#1378 ▼
  #client: Webklex\PHPIMAP\Client {#1370 ▶}
  +path: "INBOX"
  +name: "INBOX"
  +full_name: "INBOX"
  +children: []
  +delimiter: "/"
  +no_inferiors: false
  +no_select: false
  +marked: false
  +has_children: false
  +referal: false
  #events: array:2 [▶]
}
```

If I then.attempt to query the messages with ` $messages = $inbox->query()->all()->limit(2)->get();` as you indicated, I get an `Invalid argument supplied for foreach()` error coming from `vendor/webklex/php-imap/src/Query/Query.php:224`

Any idea what could be causing that? There is definitely mails in there as it's my test account I use with the old version all the time.

Also a question with regards to having to call `->all()` before limit. Does this impact the performance? I'm limiting how many mails I get each time because the clients have thousands of emails and I can't retrieve them all each time.

**Comment by Webklex** [comment] 2020-10-15 22:20
Hi @ricus-zero2one ,
you don't have to initialize a new ClientManager instance. You can just use the Facade instead:
```php
$oClient = \Webklex\IMAP\Facades\Client::make([
    'username'      => $this->username,
    'password'      => $this->password,
    'host'          => $this->host,
    'port'          => $this->port,
    'encryption'    => $this->encryption,
    'protocol'      => $this->protocol,
    'validate_cert' => $this->validate_cert,
]);
$oClient->connect();

$inbox = $oClient->getFolder('INBOX');
```

`WhereQuery::all()` just sets the imap search criteria to `ALL`. The actual messages won't get fetched until `Query::get()` is called - so writing `Query::limit()` after `WhereQuery::all()` is perfectly fine :)

Please provide the complete callstack. If you look at `Query:L224` you'll see that that's just the place where the exception was thrown, not where the error occurred. But I suspect that it might has to do with [#356](https://github.com/Webklex/laravel-imap/issues/356) which got fixed here [4995a3e](https://github.com/Webklex/php-imap/commit/4995a3e9a1c403a97cf0a710848b96c7cb91e7e6#diff-c2c223d397ff4054e697837a40251682f924f24c6a9c1278a4fd874f4835c027).

Best regards,

**Comment by DasTobbel** [comment] 2020-10-16 14:27
Hi @ricus-zero2one, if your Issue is fixed, can you close this one, please? Thanks!

**Comment by ricus-zero2one** [comment] 2020-10-22 09:59
Hi @DasTobbel - I need to still double check this. However the initial issue of config not recognised isn't applicable anymore so we can close this issue and I will open a new one if I run into any issue. Thanks

**Closed** 2020-10-22 10:19 UTC
Labels: bug, validated

**Comment by okrulik** [comment] 2021-02-13 20:22
I don't think that the issue has to be closed 
yes as a temporary solution it is acceptable to use static make the method

```
$oClient = \Webklex\IMAP\Facades\Client::make([
    'username'      => $this->username,
    'password'      => $this->password,
    'host'          => $this->host,
    'port'          => $this->port,
    'encryption'    => $this->encryption,
    'protocol'      => $this->protocol,
    'validate_cert' => $this->validate_cert,
]);
$oClient->connect();

$inbox = $oClient->getFolder('INBOX');
```

but this kind of code should work also
```
$oClient = new Client([
    'username'      => $this->username,
    'password'      => $this->password,
    'host'          => $this->host,
    'port'          => $this->port,
    'encryption'    => $this->encryption,
    'protocol'      => $this->protocol,
    'validate_cert' => $this->validate_cert,
]);
$oClient->connect();

$inbox = $oClient->getFolder('INBOX');

```

I have to manually set the default config to get it working
`ClientManager::$config=config('imap');`

**Comment by Webklex** [comment] 2021-02-14 05:45
Hi @okrulik ,
thanks for your suggestion. 

Which `Client::class` are you suggesting to use? You haven't provided any namespace.

Best regards,
